volumes:
  cache:
    driver: local

services:
  app:
    build:
      context: .
    container_name: w4t3rcs-movies
    depends_on:
      - redis
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: dzR0M3Jjcy1tb3ZpZXMtYmFja2VuZA==

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass dzR0M3Jjcy1tb3ZpZXMtYmFja2VuZA==
    volumes:
      - cache:/data